### PR TITLE
Add chrome.storage support

### PR DESCRIPTION
**Pull request by Klowner**
Not sure if you'd like to have support for chrome.storage, but I needed it for some of my tests, figured I'd submit a PR!

Thanks! :+1:

### CODE REVIEW

**Comment by sethmcl** [comment]
thanks!!

**Comment by Klowner** [comment]
whoops, I also snuck a .jscsrc in there as well. I'm happy to yank that out if you don't want it.

**Comment by sethmcl** [comment]
That would be great. After the update and a good build, I'll go ahead and merge

**Comment by Klowner** [comment]
:dancers:

**Pull request merged**
